# GitLab CI/CD configuration for Pages deployment
image: node:18

# Define stages
stages:
  - deploy

# Deploy to GitLab Pages
pages:
  stage: deploy
  script:
    - echo "Deploying to GitLab Pages..."
    # Create public directory if it doesn't exist
    - mkdir -p public
    # Copy all files to public directory (adjust based on your project structure)
    - cp -r * public/ 2>/dev/null || true
    # Remove .gitlab-ci.yml from public directory
    - rm -f public/.gitlab-ci.yml
  artifacts:
    paths:
      - public
  only:
    - main